language: node_js # set language to node_js
node_js:
  - node # use node version 8
branches:
  only:
  - master # auto build and deploy in only master branch
script: # run after installed
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install # install node module
  - npm run lint
  - npm run build:aot:prod # build project

install:
  - npm install -g firebase-tools # install firebase-cli
after_success:
  - firebase use --token ${FIREBASE_TOKEN} # set firebase token
  - firebase use --add ${PROJECT_ID} # set current project
  - firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" --only hosting # deploy project

notifications:
  email:
    on_failure: change
    on_success: change
